version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Or your desired Python version
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Running Python program..."
      - python subhra_ojha_notebook1.py # Execute your Python script
  post_build:
    commands:
      - echo "Python program execution complete."

